//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessToken
    {
        public int Id { get; set; }
        public string Token { get; set; }
        public System.DateTime exprise { get; set; }
        public int memberID { get; set; }
    
        public virtual member member { get; set; }
    }
}
